#!/usr/bin/env python3

from rich import print
from src.parser import *
from src.lexer import * 
from sys import argv, exit


def main():
    if len(argv) not in [2, 1]:
        print("Usage: algo [script]")
        exit(0)

    if len(argv) == 2:
        with open(argv[1], "r") as script:
            src = script.read()
            print(Parser(src).tokens)#.produce_ast()
    else:
        print(""" 
         ▄▄▄       ██▓      ▄████  ▒█████  
        ▒████▄    ▓██▒     ██▒ ▀█▒▒██▒  ██▒
        ▒██  ▀█▄  ▒██░    ▒██░▄▄▄░▒██░  ██▒
        ░██▄▄▄▄██ ▒██░    ░▓█  ██▓▒██   ██░
        ▓█   ▓██▒░██████▒░▒▓███▀▒░ ████▓▒░
        ▒▒   ▓▒█░░ ▒░▓  ░ ░▒   ▒ ░ ▒░▒░▒░ 
         ▒   ▒▒ ░░ ░ ▒  ░  ░   ░   ░ ▒ ▒░ 
         ░   ▒     ░ ░   ░ ░   ░ ░ ░ ░ ▒  
             ░  ░    ░  ░      ░     ░ ░  
                                          
     Tunisian shitty pseudo/programming language

    Type "exit", "quit" to quit 
         "help", "credits" for more information

    Algo v0.1
    """)
        while True:
            try:
                prompt = input(">> ")
                if prompt.upper() in ["EXIT", "QUIT"]: exit()
                program = Parser(prompt).produce_ast()
                # program = Parser(prompt).tokens
                print(program)
            except KeyboardInterrupt:
                exit()
            except EOFError:
                exit()


if __name__ == "__main__":
    main()
